### ISSUE TITLE
go get -u github.com/Azure/azure-amqp-common-go/... fails

### ISSUE THREAD

**Issue by ijt** [Azure/azure-amqp-common-go#26]
### Expected Behavior
`$ go get -u github.com/Azure/azure-amqp-common-go/...` should run without failing.

### Actual Behavior
It outputs this error message:
```
# github.com/Azure/azure-amqp-common-go/aad
../../src/github.com/Azure/azure-amqp-common-go/aad/jwt.go:203:44: cannot use token.ExpiresOn (type json.Number) as type string in argument to strconv.ParseInt
../../src/github.com/Azure/azure-amqp-common-go/aad/jwt.go:216:69: cannot use token.ExpiresOn (type json.Number) as type string in argument to auth.NewToken
```

### Environment
- OS: Debian GNU/Linux
- Go version: go1.11rc2 linux/amd64
- Version of Library: dead23a10516c64bf754a2aabc7063304adcf736

**Comment by devigned** [comment]
@jhendrixMSFT just a heads up. This was caused by a breaking change in go autorest.

**Comment by jhendrixMSFT** [comment]
Sorry about this, the breaking change was necessary to fix https://github.com/Azure/go-autorest/issues/325.

**Comment by devigned** [comment]
Right on, @jhendrixMSFT. Can't wait for us to move over to modules.
