### ISSUE TITLE
support for passing managed identity client id

### ISSUE THREAD

**Issue by smuthusa** [Azure/azure-amqp-common-go#44]
When Azure VM is assigned more than one managed identity, the Azure AD expects the client id to be used for generating an auth token. Currently, azure-amqp-common-go is not considering the clientID when using MSI authentication. 

### Expected Behavior
managed identity based  authentication should consider the ClientId when not empty

### Environment
- Version of Library: 2.1.0

**Comment by jhendrixMSFT** [comment]
Fixed in v3.1.0, thanks for the PR.
